---
- name: Basic VMware playbook to get info and add tags
  hosts: localhost
  vars:
    vmware_server: server
    vmware_username: username
    vmware_password: password

  tasks:
    - name: Get VM information
      community.vmware.vmware_vm_info:
        hostname: "{{ vmware_server }}"
        username: "{{ vmware_username }}"
        password: "{{ vmware_password }}"
        validate_certs: false
        # show_tag: true
      register: vm_lists

    - name: Print VM information
      ansible.builtin.debug:
        var: vm_lists

    - name: Add tags
      community.vmware.vmware_tag_manager:
        hostname: "{{ vmware_server }}"
        username: "{{ vmware_username }}"
        password: "{{ vmware_password }}"
        validate_certs: false
        tag_names:
          - sample_tag
          - Category_0001:Sample_Tag_0003
        object_name: tower.example.local
        object_type: VirtualMachine
        state: add
      delegate_to: localhost
