---
- name: Ping hosts
  hosts: all
  gather_facts: false
  connection: local

  tasks:
    - name: Ping host
      ansible.builtin.command: "ping -i 0.2 -w 1 {{ inventory_hostname }}"
      changed_when: false
