# Ansible Lint triggered via GitHub Actions
# https://github.com/marketplace/actions/run-ansible-lint
# https://docs.github.com/en/actions/quickstart

name: ansible-lint
on: [push, pull_request]
jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
